# Site
name: Coding Friki
description: Coding Friki
meta_description: Coding Friki
logo: /assets/images/iconfinder_shining_mix_coffee_1059392.ico
favicon: /assets/images/iconfinder_shining_mix_coffee_1059392.ico
paginate: 6
baseurl: 
email: 'kenarenterprise@outlook.com'
google_analytics:
disqus: codingfriki-com
sharethis:

# Authors
authors:
  Kenar716:
    name: Kenar716
    display_name: Kenar716
    image: /assets/images/CommandoKenar716.png
    email: kenarenterprise@outlook.com
    web: www.codingfriki.com
    twitter: Kenar716
    description: Kenar716

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-feed

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: Kenar716
  card: summary

social:
  name: Kenar716
  links:
    - https://twitter.com/
    - https://github.com/
